config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/mattiaBarbo/Pipeline_Test:
      branch: main
      repo: https://github.com/mattiaBarbo/Pipeline_Test
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/mattiaBarbo/Pipeline_Test git:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-alizarin-spaniel.sh
        container: qc.acc_skinny-charcoal-squirrel
  QC.Doc:
    repos:
      github.com/mattiaBarbo/Pipeline_Test find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-champagne-newt.sh
        container: qc.doc_queasy-wisteria-clam
      github.com/mattiaBarbo/Pipeline_Test git:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-fuchsia-chicken.sh
        container: qc.doc_foggy-red-spaniel
      github.com/mattiaBarbo/Pipeline_Test markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-russet-grasshopper.sh
        container: qc.doc_cloudy-crimson-weasel
  QC.Lic:
    repos:
      github.com/mattiaBarbo/Pipeline_Test licensee:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-amaranth-bison.sh
        container: qc.lic_crappy-buff-gharial
  QC.Sec:
    repos:
      github.com/mattiaBarbo/Pipeline_Test bandit:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-rose-spoonbill.sh
        container: qc.sec_crabby-celadon-birman
  QC.Sty:
    repos:
      github.com/mattiaBarbo/Pipeline_Test flake8:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-gamboge-wombat.sh
        container: qc.sty_skinny-pear-buffalo
  QC.Uni:
    repos:
      github.com/mattiaBarbo/Pipeline_Test pytest:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-dandelion-peccary.sh
        container: qc.uni_shaky-wisteria-sponge
  QC.Ver:
    repos:
      github.com/mattiaBarbo/Pipeline_Test get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-cream-dingo.sh
        container: qc.ver_grumpy-orchid-antelope
timeout: 5400
