config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/mattiaBarbo/Pipeline_Test:
      branch: main
      repo: https://github.com/mattiaBarbo/Pipeline_Test
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/mattiaBarbo/Pipeline_Test git:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-celadon-lion.sh
        container: qc.acc_snazzy-olivine-caiman
  QC.Doc:
    repos:
      github.com/mattiaBarbo/Pipeline_Test find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-seashell-sponge.sh
        container: qc.doc_stealthy-khaki-kingfisher
      github.com/mattiaBarbo/Pipeline_Test git:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-lemon-vole.sh
        container: qc.doc_jumpy-sangria-capybara
      github.com/mattiaBarbo/Pipeline_Test markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-lemon-mongoose.sh
        container: qc.doc_greasy-cinnabar-quail
  QC.Lic:
    repos:
      github.com/mattiaBarbo/Pipeline_Test licensee:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-violet-lizard.sh
        container: qc.lic_snappy-eggplant-vole
  QC.Sec:
    repos:
      github.com/mattiaBarbo/Pipeline_Test bandit:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-periwinkle-wildebeest.sh
        container: qc.sec_gamy-goldenrod-okapi
  QC.Sty:
    repos:
      github.com/mattiaBarbo/Pipeline_Test flake8:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-azure-oyster.sh
        container: qc.sty_queasy-denim-opossum
  QC.Uni:
    repos:
      github.com/mattiaBarbo/Pipeline_Test pytest:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-cerulean-mandrill.sh
        container: qc.uni_tacky-thistle-cockroach
  QC.Ver:
    repos:
      github.com/mattiaBarbo/Pipeline_Test get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-tangerine-shrew.sh
        container: qc.ver_pasty-razzmatazz-camel
timeout: 5400
